name = "poll-api-staging"
main = "src/index.ts"
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
    { binding = "TEST", id = "your-kv-id" },
]

###DONT add preview id
