name = "poll-api-staging"
main = "src/index.ts"
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
    { binding = "USER_PROFILE_INTERACTICO", id = "64cbc600878a472499604a72f7d053ed" },
]

###DONT add preview id
